version: "1.0"

services:
  mongo:
    image: mongo
    ports:
      -  "27017:27017"
    volumes:
      - /home/omega/learning_mat/isp-ta/todo101-ISP-2025/backend/data/db
  todo-backend:
    build: ./backend
    ports:
      - "15000:15000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
    depends_on:
      - mongo
  todo-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - todo-backend
